### ISSUE TITLE
Related project gst-plugins-vision

### ISSUE THREAD

**Issue by joshdoe** [zingmars/gst-pylonsrc#10]
Hello, I have a project [gst-plugins-vision][1] that contains many video source plugins for interfaces like Camera Link, GigE Vision, USB3 Vision, etc. I currently have support for GigE Vision via National Instruments IMAQdx, Matrox, Pleora, and IDS uEye. The last one only works with IDS uEye cameras, and the first four require a license (unless you have a Pleora-powered device).

I'm planning to create a plugin for Basler cameras, however I just came across your project here. I've been focusing on supporting Windows devices, though most plugins should be able to be built on Linux without too much effort (at least if the corresponding SDK supports it!). I imagine the same is true for your project, I believe Pylon should work nearly the same on Windows.

I use CMake for my build system (though might add support for meson soon), and would need to do so for your project. I'm opening this issue to get your thoughts on how best to incorporate your project. Just fork your code to my project (both are LGPL projects), or add CMake to your project and do any necessary fixes to get Windows supported.

Thanks for open sourcing your work!

[1]: https://github.com/joshdoe/gst-plugins-vision

**Comment by zingmars** [comment]
Hey,

Honestly both ways sounds good to me, so do whichever is easier for you. I'll be glad to accept any PRs you send my way if you decide to do so.

**Comment by joshdoe** [comment]
@zingmars to make it clear, you're receptive to patches for adding CMake build files and supporting Windows?

**Comment by zingmars** [comment]
As long as the build process is documented (i.e. in README) I have no issues with this

**Comment by joshdoe** [comment]
@zingmars I've forked your project and got it building in Visual Studio on Windows using CMake, and tested with several GigE cameras:
https://github.com/joshdoe/gst-pylonsrc/tree/cmake_windows

Do you consider this to be an actively maintained project? I'm considering pulling your plugin into my gst-plugins-vision project, which is a project I am actively maintaining. I at least wanted to share the changes I've made to date.

**Comment by zingmars** [comment]
> Do you consider this to be an actively maintained project

Nope, in fact I no longer have any access to Basler-made equipment, so my ability to do anything is fairly limited. I mostly just provide support to people who need it (sometimes Basler rep comes in and helps too). For what it's worth the plugin is stable, the only issue being that it doesn't implement a few camera features (i.e. https://github.com/zingmars/gst-pylonsrc/issues/16). If you feel like maintaining it, I'll add a link to your repo in the README.

**Comment by joshdoe** [comment]
Ok, I've merged it in. It's working now, just changing some things to align it with my other plugins. Thanks for all the great work you've done, it's a great help! 

https://github.com/joshdoe/gst-plugins-vision

About to add support for some other pixel formats, and avoid memcpy.
