### ISSUE TITLE
Cannot find proper location on Jeston baord

### ISSUE THREAD

**Issue by jahwanoh** [zingmars/gst-pylonsrc#14]
I'm using Jetson board  and cannot find gstreamer-1.0/ folder...
do you have any experience related with this?

> To install manually you need copy, move or symlink the following files
> 
> ./plugins/libgstpylonsrc.la
> ./plugins/.libs/libgstpylonsrc.so
> to either of these locations:
> 
> ~/.local/share/gstreamer-1.0/plugins/ if you only want your user to be able to use this plugin
> /usr/local/lib/gstreamer-1.0/ if you want this plugin to be available to every user.
> Note that these are the default locations which might be different if you installed gstreamer with a custom location prefix.

**Comment by zingmars** [comment]
Which Linux distribution are you running?

The first directory (`~/.local/share/gstreamer-1.0/plugins/`) must be created manually most of the time. The latter might not exist if you only have the distribution's version of gstreamer. For that the location of plugins depends on where gstreamer is installed, I think (`/usr/lib/gstreamer-1.0`?).

**Comment by jahwanoh** [comment]
I managed to find one below. I will try to follow the last instructions.
1. ubuntu 14.08 for host pc
 /usr/lib/x86_64-linux-gnu/gstreamer-1.0

2. and Jetson Xavier.
/usr/lib/aarch64-linux-gnu/gstreamer-1.0

**Comment by jahwanoh** [comment]
hm, actually I tried it again. I use `sudo make install` in the gst-pylonsrc/plugins directory.
I think it was installed correctly.

```
:/usr/local/lib/gstreamer-1.0$ ls -al
total 1128
drwxr-xr-x 2 root root   4096 Oct 10 20:33 .
drwxr-xr-x 6 root root  12288 Oct 10 14:23 ..
-rw-r--r-- 1 root root  74972 Oct 10 20:33 libgstfpsfilter.a
-rwxr-xr-x 1 root root   1105 Oct 10 20:33 libgstfpsfilter.la
-rwxr-xr-x 1 root root  53504 Oct 10 20:33 libgstfpsfilter.so
-rw-r--r-- 1 root root 654966 Oct 10 20:33 libgstpylonsrc.a
-rwxr-xr-x 1 root root   1098 Oct 10 20:33 libgstpylonsrc.la
-rwxr-xr-x 1 root root 338800 Oct 10 20:33 libgstpylonsrc.so

```

**Comment by zingmars** [comment]
You can test it with `gst-inspect-1.0 pylonsrc`.

**Comment by jahwanoh** [comment]
gst-launch-1.0 -v pylonsrc camera=1 fps=25 ! bayer2rgb ! nvvidconv ! 'video/x-raw(memory:NVMM), format=NV12' ! omxh265enc ! matroskamux ! filesink location=test_1_265.mp4 -e

it worked fine with above. Thank you.

**Comment by zingmars** [comment]
Depending on your camera you might be able to use the `imageformat` parameter for pylonsrc to output rgb directly. [See supported formats](https://github.com/zingmars/gst-pylonsrc#formats).
