### ISSUE TITLE
HW triggering parameter

### ISSUE THREAD

**Issue by jahwanoh** [zingmars/gst-pylonsrc#15]
> There are two modes for picture capture - trigger mode and continuous. Trigger mode asks for each frame seperately which while continuous mode makes the camera capture frames without software input. Continuous is default, but it can be disabled by setting the continuous parameter to false (default - true).
I'm trying to implement panorama video application using this api.

reading this, the Trigger mode sounds like hw triggering. then, should I set the trigger line parameters using pylonviewerapp, and then set the continuous=false in the gstreamer pipeline?

Thank you.

**Comment by zingmars** [comment]
Yeah, pretty much.
