### ISSUE TITLE
No such element or plugin 'pylonsrc'

### ISSUE THREAD

**Issue by harendracmaps** [zingmars/gst-pylonsrc#17]
I have compiled adn installed the libraries. but while running the following command 
gst-inspect-1.0 pylonsrc

I am facing the issue and pylonsrc is not getting detected.
 
No such element or plugin 'pylonsrc'.

Any help would be appreciated.

**Comment by zingmars** [comment]
Linux distribution? Gstreamer version? How was gstreamer installed? Where is gstreamer installed? Is the plugin's .so file available in `/usr/local/lib/gstreamer-1.0/` or `~/.local/share/gstreamer-1.0/plugins/`? What happens if you run `gst-inspect-1.0` with a path to the .so file? What was the output of `sudo make install`?

**Comment by harendracmaps** [comment]
Thanks for responding. please fine the details as below.
Linux : ARM64 
GSTREAMER VERSION : GStreamer 1.8.3
gstreamer was installed using apt-get command.

root@jetson-tx2-01:/persistent/gst-pylonsrc# ls /usr/local/lib/gstreamer-1.0/
----
libgstfpsfilter.a   libgstfpsfilter.so  libgstpylonsrc.la  libgstrtspclientsink.la
libgstfpsfilter.la  libgstpylonsrc.a    libgstpylonsrc.so  libgstrtspclientsink.so

root@jetson-tx2-01:/persistent/gst-pylonsrc# gst-inspect-1.0 /usr/local/lib/gstreamer-1.0/libgstpylonsrc.so
-------
Plugin Details:
  Name                     pylonsrc
  Description              A plugin that uses Basler's pylon5 to get data from Basler's USB3 Vision cameras.
  Filename                 /usr/local/lib/gstreamer-1.0/libgstpylonsrc.so
  Version                  1.1.0
  License                  LGPL
  Source module            gst-pylonsrc
  Binary package           gst-pylonsrc
  Origin URL               http://www.playgineering.com/

  pylonsrc: Basler's Pylon5 for Gstreamer

  1 features:
  +-- 1 elements

root@jetson-tx2-01:/persistent/gst-pylonsrc# gst-inspect-1.0 pylonsrc
------
No such element or plugin 'pylonsrc'

sudo make install was success.

**Comment by zingmars** [comment]
Did you clear gstreamer cache? `rm -rf ~/.cache/gstreamer-1.0` should do it iirc. Try gst-inspect-1.0 again after cleaning it. If not, note you'll need to clean the cache before you try do run any of the suggestions below.

If it doesn't work, does the rtspclientsink plugin you have in that directory show up when you try to gst-inspect-1.0 the plugin added by `libgstrtspclientsink.so`? If you move pylonsrc's .la and .so files to `~/.local/share/gstreamer-1.0/plugins`, does it show up then?
Does it work if you add `GST_PLUGIN_SYSTEM_PATH=/usr/local/lib/gstreamer-1.0/` before the gst-inspect command (i.e. `GST_PLUGIN_SYSTEM_PATH=/usr/local/lib/gstreamer-1.0/ gst-inspect-1.0 pylonsrc`). Also try setting `GST_PLUGIN_SYSTEM_PATH_1_0`, `GST_PLUGIN_PATH` and `GST_PLUGIN_PATH_1_0` variables with the same path. Also, you can also try the `GST_DEBUG=*:6` environmental with gst-inspect-1.0 and see if that outputs anything useful (i.e. which paths your gstreamer scans for plugins).

**Comment by harendracmaps** [comment]
Thanks !
Cleaning the cache does not solve the issue. But moving the *.so *.la in path ~/.local/share/gstreamer-1.0/plugins solved. Also if I set GST_PLUGIN_SYSTEM_PATH to /usr/local/lib/gstreamer-1.0/. then also it is working.

**Comment by harendracmaps** [comment]
Thanks !
Cleaning the cache does not solve the issue. But moving the *.so *.la in path ~/.local/share/gstreamer-1.0/plugins solved. Also if I set GST_PLUGIN_SYSTEM_PATH to /usr/local/lib/gstreamer-1.0/. then also it is working.

**Comment by harendracmaps** [comment]
even though I closed the issue looks like it is not completely resolved. Either I am missing something in the command.

gst-launch-1.0 -v pylonsrc ! bayer2rgb ! videoconvert ! xvimagesink
-----
WARNING: erroneous pipeline: no element "bayer2rgb"

gst-launch-1.0 pylonsrc imageformat=ycbcr422_8 width=1280 height=720 ! videorate ! video/x-raw, framerate=5/1 ! videoconvert !  x264enc ! rtph264pay ! udpsink port=554
---
WARNING: erroneous pipeline: no element "videorate"

**Comment by zingmars** [comment]
First pipeline - you probably don't need the bayer2rgb. The camera I was using didn't have rgb output support (it was an early marketing sample). It should default to rgb and run just fine.

Second pipeline - Seems like your distro does not ship that plugin (it should be part of gst-plugins-base) or you don't have base plugins installed. You'll have to refer to your Linux distros documentations for that.
