### ISSUE TITLE
limitbandwidth not implemented for all cameras?

### ISSUE THREAD

**Issue by petergerten** [zingmars/gst-pylonsrc#2]
Software: pylon 5.0.12 Camera Software Suite Linux x86 (64 bit)
Camera: acA720-520uc

When using the "limitbandwidth" parameter in the above setup I get:
`WARNING: erroneous pipeline: could not set property "limitbandwidth" in element "pylonsrc0" to "off"`

Is limitbandwidth not implemented for all cameras, or maybe got renamed? 
I can see that a default camera bandwidthlimit of ~300MB/s is active.

**Comment by zingmars** [comment]
There's a typo in the README. It's a boolean value, so true/false should work.

**Comment by petergerten** [comment]
thanks, I should have figured that out myself. It's working now.
