### ISSUE TITLE
Can't set continuous to false

### ISSUE THREAD

**Issue by chiuwe** [zingmars/gst-pylonsrc#9]
Hi,
I can't seem to set continuous to false. Whenever I do it crashes.
```
gst-launch-1.0 pylonsrc imageformat=ycbcr422_8 continuous=0 width=1920 height=1080 ! videorate ! video/x-raw, framerate=5/1 ! videoconvert ! autovideosink
Setting pipeline to PAUSED ...
0:00:01.084715768 120211 0x55a38aedf990              pylonsrc gstpylonsrc.c:2235:pylonc_print_camera_info:<pylonsrc0> Status: Using camera "daA2500-14uc" (serial number: 40011783, id: 0). Custom ID: None
0:00:01.114690408 120211 0x55a38aedf990              pylonsrc gstpylonsrc.c:1093:gst_pylonsrc_start:<pylonsrc0> Setting resolution to 1920x1080.
0:00:01.119438100 120211 0x55a38aedf990              pylonsrc gstpylonsrc.c:1217:gst_pylonsrc_start:<pylonsrc0> Using YCbCr422_8 image format.
0:00:01.183060782 120211 0x55a38aedf990              pylonsrc gstpylonsrc.c:1920:gst_pylonsrc_start:<pylonsrc0> PylonC error: PylonC error #c2000005 'There is no node named 'AcquisitionStatusSelector'' (0xc2000005).

0:00:01.183179846 120211 0x55a38aedf990              pylonsrc gstpylonsrc.c:1920:gst_pylonsrc_start:<pylonsrc0> PylonC error: Function 'GenApiNodeMapGetNodeWithCheck' failed in source file '/home/jenkins/workspace/pylon_release_5.2/Pylon/PylonC/PylonC/ImplHelpers.h' line #226

ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstPylonsrc:pylonsrc0: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.
Additional debug info:
gstbasesrc.c(3452): gst_base_src_start (): /GstPipeline:pipeline0/GstPylonsrc:pylonsrc0:
Failed to start
Setting pipeline to NULL ...
Freeing pipeline ...
```

**Comment by zingmars** [comment]
`0:00:01.183179846 120211 0x55a38aedf990              pylonsrc gstpylonsrc.c:1920:gst_pylonsrc_start:<pylonsrc0> PylonC error: Function 'GenApiNodeMapGetNodeWithCheck' failed in source file '/home/jenkins/workspace/pylon_release_5.2/Pylon/PylonC/PylonC/ImplHelpers.h' line #226` Looks like an issue with Pylon. Maybe they updated the API? Hard to tell.

 Could you please try downloading 5.0.11 from Basler's website and try again?

**Comment by MattsProjects** [comment]
FYI, This camera model does not have the 'AcquisitionStatusSelector'' feature.

Best Regards,

Matt




Matthew Breit
Senior Consulting Engineer & Market Analyst
          [https://www.baslerweb.com/baslermedia/socialmediaicons_email_signature/AIA_CVP_Advanced_Logo_67px.png]
[BASLER-Logo_for_Signature]<https://www.baslerweb.com/?utm_medium=email&utm_source=basler-internal&utm_content=basler%20logo>

Basler Inc.

855 Springdale Drive, Suite 203
Exton, PA 19341
United States

Tel. +1 610 717 5506
Fax +1 610 280 7608
Matthew.Breit@baslerweb.com
<http://www.baslerweb.com>www.baslerweb.com<https://www.baslerweb.com/?utm_medium=email&utm_source=basler-internal&utm_content=basler%20text>

[https://www.baslerweb.com/baslermedia/socialmediaicons_email_signature/facebook_blue.gif]<http://www.facebook.com/BaslerAG>  [https://www.baslerweb.com/baslermedia/socialmediaicons_email_signature/twitter_blue.gif] <https://twitter.com/Basler_AG>   [https://www.baslerweb.com/baslermedia/socialmediaicons_email_signature/linkedin_blue.gif] <https://www.linkedin.com/company/basler-ag>   [https://www.baslerweb.com/baslermedia/socialmediaicons_email_signature/youtube_blue.gif] <http://www.youtube.com/user/BaslerAG>   [https://www.baslerweb.com/baslermedia/socialmediaicons_email_signature/xing_blue.gif] <https://www.xing.com/companies/baslerag>   [https://www.baslerweb.com/baslermedia/socialmediaicons_email_signature/imaginghub_blue.gif] <https://imaginghub.com/partners/category-hardware/51-basler-ag>
On Jul 26, 2019, at 7:15 PM, Steven Chiu <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I can't seem to set continuous to false. Whenever I do it crashes.

gst-launch-1.0 pylonsrc imageformat=ycbcr422_8 continuous=0 width=1920 height=1080 ! videorate ! video/x-raw, framerate=5/1 ! videoconvert ! autovideosink
Setting pipeline to PAUSED ...
0:00:01.084715768 120211 0x55a38aedf990 pylonsrc gstpylonsrc.c:2235:pylonc_print_camera_info: Status: Using camera "daA2500-14uc" (serial number: 40011783, id: 0). Custom ID: None
0:00:01.114690408 120211 0x55a38aedf990 pylonsrc gstpylonsrc.c:1093:gst_pylonsrc_start: Setting resolution to 1920x1080.
0:00:01.119438100 120211 0x55a38aedf990 pylonsrc gstpylonsrc.c:1217:gst_pylonsrc_start: Using YCbCr422_8 image format.
0:00:01.183060782 120211 0x55a38aedf990 pylonsrc gstpylonsrc.c:1920:gst_pylonsrc_start: PylonC error: PylonC error #c2000005 'There is no node named 'AcquisitionStatusSelector'' (0xc2000005).

0:00:01.183179846 120211 0x55a38aedf990 pylonsrc gstpylonsrc.c:1920:gst_pylonsrc_start: PylonC error: Function 'GenApiNodeMapGetNodeWithCheck' failed in source file '/home/jenkins/workspace/pylon_release_5.2/Pylon/PylonC/PylonC/ImplHelpers.h' line #226

ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstPylonsrc:pylonsrc0: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.
Additional debug info:
gstbasesrc.c(3452): gst_base_src_start (): /GstPipeline:pipeline0/GstPylonsrc:pylonsrc0:
Failed to start
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by chiuwe** [comment]
Hi Matt,

This is the camera that i'm using. https://www.baslerweb.com/en/products/cameras/area-scan-cameras/dart/daa2500-14uc-s-mount/#tab=specs
it says it supports software trigger.
How do enable software trigger when this camera doesn't support 'AcquisitionStatusSelector'?

BR,
SC

**Comment by MattsProjects** [comment]
Hi Steven,
The software trigger can still be used, it’s just that the WaitForFrameTriggerReady() call which depends on AcqusitionStatus cannot be used.
In other words, the timing of when a trigger can be sent must be manually managed (ie: after a frame has been received, it is of course ok to send the next trigger).

Best Regards,
Matt




Matthew Breit
Senior Consulting Engineer & Market Analyst
          [https://www.baslerweb.com/baslermedia/socialmediaicons_email_signature/AIA_CVP_Advanced_Logo_67px.png]
[BASLER-Logo_for_Signature]<https://www.baslerweb.com/?utm_medium=email&utm_source=basler-internal&utm_content=basler%20logo>

Basler Inc.

855 Springdale Drive, Suite 203
Exton, PA 19341
United States

Tel. +1 610 717 5506
Fax +1 610 280 7608
Matthew.Breit@baslerweb.com
<http://www.baslerweb.com>www.baslerweb.com<https://www.baslerweb.com/?utm_medium=email&utm_source=basler-internal&utm_content=basler%20text>

[https://www.baslerweb.com/baslermedia/socialmediaicons_email_signature/facebook_blue.gif]<http://www.facebook.com/BaslerAG>  [https://www.baslerweb.com/baslermedia/socialmediaicons_email_signature/twitter_blue.gif] <https://twitter.com/Basler_AG>   [https://www.baslerweb.com/baslermedia/socialmediaicons_email_signature/linkedin_blue.gif] <https://www.linkedin.com/company/basler-ag>   [https://www.baslerweb.com/baslermedia/socialmediaicons_email_signature/youtube_blue.gif] <http://www.youtube.com/user/BaslerAG>   [https://www.baslerweb.com/baslermedia/socialmediaicons_email_signature/xing_blue.gif] <https://www.xing.com/companies/baslerag>   [https://www.baslerweb.com/baslermedia/socialmediaicons_email_signature/imaginghub_blue.gif] <https://imaginghub.com/partners/category-hardware/51-basler-ag>
